### ISSUE TITLE
Does not work correctly with different locales

### ISSUE THREAD

**Issue by chinarad** [ale18V/Anki-Multiple-Choice#1] opened 2023-08-08 13:02 UTC
I’ve tried both templates but they don’t work.

Can you please help? 
I use AnkiMobile for iPhone version 2.0.96 (20096.3)

![IMG_0079](https://github.com/ale18V/Anki-Multiple-Choice/assets/79573055/28786eb2-94d5-48b7-95c0-2b92fe16dcd9)

![IMG_0078](https://github.com/ale18V/Anki-Multiple-Choice/assets/79573055/d7664cce-8d54-4c68-ab2a-877c5d295afa)

**Comment by ale18V** [comment] 2023-08-09 08:37
Hi, I can't reproduce the issue.
I use Anki Mobile 2.0.96 on Iphone as well and everything is working fine.
Can you please include pictures of the card model's front and backside?

**Comment by chinarad** [comment] 2023-08-09 16:04
Front
![IMG_0123](https://github.com/ale18V/Anki-Multiple-Choice/assets/79573055/2c4fb221-9f91-4b78-a577-1dc1dfa0746f)

Back
![IMG_0124](https://github.com/ale18V/Anki-Multiple-Choice/assets/79573055/801db988-8951-4ba6-9bfe-9ab79a02baa1)

**Comment by ale18V** [comment] 2023-08-09 17:00
It looks like the problem is {{FrontSide}}.
This is because when you use {{FrontSide}} you also include the scripts of the front of the card.
Try to substitute it with, for example, {{Front}} and let me know if it works.
I'll see if it is possible to avoid this issue in the meantime.

**Comment by chinarad** [comment] 2023-08-09 17:31
I deleted {{Frontside}}

Doesn’t work either. 

Now the cards look like this:

Front:

![IMG_0127](https://github.com/ale18V/Anki-Multiple-Choice/assets/79573055/96c10ace-0842-4c00-be6a-2520bf58caef)

Back:

![IMG_0126](https://github.com/ale18V/Anki-Multiple-Choice/assets/79573055/c089e05d-db11-492d-9300-7fe8c3396d62)

**Comment by chinarad** [comment] 2023-08-09 17:35
Here I tried to substitute {{Frontside}} by {{Front}}

Doesn’t work either 😢

![IMG_0129](https://github.com/ale18V/Anki-Multiple-Choice/assets/79573055/d1fcfaf1-1dbf-4d30-9fd0-22b137523011)

And here is how my Fields filled: 

![IMG_0128](https://github.com/ale18V/Anki-Multiple-Choice/assets/79573055/325d837c-b891-4b7e-b3d2-19486d98700c)

**Comment by chinarad** [comment] 2023-08-09 17:42
Here is my ankg file. Can you correct it, please, and send me back. [apkg](https://drive.google.com/file/d/1YxEOpA8qTNzPBl5XNwAt6SMTihnQPEpr/view?usp=drivesdk)

**Comment by ale18V** [comment] 2023-08-09 19:05
Thanks for sharing the apkg, it probably would have been impossible to debug otherwise.
It seems that there were some problems with how anki handles different locales.
I've now fixed the problem, so if you copy the updated files it should work.
Keep in mind, though, that I've not fixed the {{FrontSide}} thing yet.

**Comment by chinarad** [comment] 2023-08-10 07:35
Thank tou for your help. Now it generally works, but some other bugs occur: 


1. In template 1 sometimes it shows empty choice: 

![IMG_0147](https://github.com/ale18V/Anki-Multiple-Choice/assets/79573055/3d01a2ce-d8d1-4517-8b18-057a0008fd16)

2. In template 2 sometimes it shows a line instead of button: 

![IMG_0149](https://github.com/ale18V/Anki-Multiple-Choice/assets/79573055/4a4b2517-eec6-46c3-949f-d1a5568ca5d2)

3. In template 2 when you click buttons on Front side it doesn’t make it green or red but only make it bordered in blue:

![IMG_0150](https://github.com/ale18V/Anki-Multiple-Choice/assets/79573055/8387b601-0244-4224-ad63-e6c4939717c7)

And then when you tap second time it make it red or green. 

Here is my apkg file as well.
[Click here for file](https://drive.google.com/file/d/13DUmbn6XUjBkZYjTpHkzPMjUFqmd6Kuf/view?usp=drivesdk)

**Comment by ale18V** [comment] 2023-08-10 17:42
Regarding 1) and 2): You are getting empty buttons because there's an empty line at the end of the choices fields (after choice 8). This is not a bug because every line is treated as a valid choice, even an empty line, which is effectively considered an empty choice.

Regarding point 3), it's not a bug; it's the design of the template. The card displays the correct answer only when flipped and does not flip automatically when a choice is selected. This information is documented in the README file. If it's unclear, I'll edit the file to make it more explicit.

That being said, thank you for opening this issue. I will monitor it and close it within a few days if no further problems arise.

**Comment by chinarad** [comment] 2023-08-10 20:11
Yes, you were right; there were an empty line. Maybe you should mention it and aware of it in your read me files somebody not to be confused.

And could you change showing a line instead of empty button in template 2 anyway.

And thank your for your help and work.

**Comment by ale18V** [comment] 2023-08-10 21:40
I've updated the code so that now empty lines get ignored.
Thinking back on the matter I realized that it's probably better this way as nobody would want to use empty choices anyways.
This will prevent apparently unexpected behaviours, especially in case of copy-pasting. You can find the updated templates inside the `dist` folder.

**Comment by chinarad** [comment] 2023-08-12 18:16
Have you also corrected this bug as well - showing just line instead of button? 
![image](https://github.com/ale18V/Anki-Multiple-Choice/assets/79573055/e672701f-cb72-4d45-bbe9-fb0248041eff)

**Comment by ale18V** [comment] 2023-08-19 21:11
Yes it should not show an empty line now, as that was caused by the choice being empty.
I'll close this issue now, If you experience further problems, feel free to open another one

**Closed as completed** 2023-08-19 21:14 UTC
